/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mox.nbevid.explorer.editors;


import java.awt.Image;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JToolBar;
import mox.nbevid.explorer.nodes.DbInfo;
import mox.nbevid.model.YearMonth;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewDescription;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.UndoRedo;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;


/**
 *
 * @author martin
 */
public class MonthEditorPanel extends javax.swing.JPanel implements MultiViewElement {
  private static final long serialVersionUID = 1L;
  
  private MultiViewElementCallback callback;

  private final JToolBar toolbar = new JToolBar();
  
  private final YearMonth month;
  private final DbInfo dbInfo;
  private final Lookup lookup;

  /**
   * Creates new form MonthEditorPanel
   */
  public MonthEditorPanel(YearMonth month, DbInfo dbInfo) {
    this.month = month;
    this.dbInfo = dbInfo;
    this.lookup = Lookups.fixed(month, dbInfo);
    
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    splitPane = new javax.swing.JSplitPane();
    itemsOverviewScrollPane = new javax.swing.JScrollPane();
    itemEditPanel = new javax.swing.JPanel();
    itemLabel = new javax.swing.JLabel();
    itemsComboBox = new javax.swing.JComboBox<>();
    itemValueFormattedTextField = new javax.swing.JFormattedTextField();
    addValueButton = new javax.swing.JButton();
    resetValueButton = new javax.swing.JButton();

    splitPane.setDividerLocation(200);
    splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
    splitPane.setContinuousLayout(true);
    splitPane.setOneTouchExpandable(true);
    splitPane.setTopComponent(itemsOverviewScrollPane);

    org.openide.awt.Mnemonics.setLocalizedText(itemLabel, org.openide.util.NbBundle.getMessage(MonthEditorPanel.class, "MonthEditorPanel.itemLabel.text", new Object[] {})); // NOI18N

    itemsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    itemValueFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
    itemValueFormattedTextField.setText(org.openide.util.NbBundle.getMessage(MonthEditorPanel.class, "MonthEditorPanel.itemValueFormattedTextField.text", new Object[] {})); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(addValueButton, org.openide.util.NbBundle.getMessage(MonthEditorPanel.class, "MonthEditorPanel.addValueButton.text", new Object[] {})); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(resetValueButton, org.openide.util.NbBundle.getMessage(MonthEditorPanel.class, "MonthEditorPanel.resetValueButton.text", new Object[] {})); // NOI18N

    javax.swing.GroupLayout itemEditPanelLayout = new javax.swing.GroupLayout(itemEditPanel);
    itemEditPanel.setLayout(itemEditPanelLayout);
    itemEditPanelLayout.setHorizontalGroup(
      itemEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(itemEditPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(itemLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(itemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(itemValueFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(addValueButton)
        .addGap(18, 18, 18)
        .addComponent(resetValueButton)
        .addContainerGap(153, Short.MAX_VALUE))
    );
    itemEditPanelLayout.setVerticalGroup(
      itemEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(itemEditPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(itemEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(itemLabel)
          .addComponent(itemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(itemValueFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(addValueButton)
          .addComponent(resetValueButton))
        .addContainerGap(348, Short.MAX_VALUE))
    );

    splitPane.setRightComponent(itemEditPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(splitPane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addValueButton;
  private javax.swing.JPanel itemEditPanel;
  private javax.swing.JLabel itemLabel;
  private javax.swing.JFormattedTextField itemValueFormattedTextField;
  private javax.swing.JComboBox<String> itemsComboBox;
  private javax.swing.JScrollPane itemsOverviewScrollPane;
  private javax.swing.JButton resetValueButton;
  private javax.swing.JSplitPane splitPane;
  // End of variables declaration//GEN-END:variables

  @Override
  public JComponent getVisualRepresentation() {
    return this;
  }

  @Override
  public JComponent getToolbarRepresentation() {
    return toolbar;
  }

  @Override
  public Action[] getActions() {
    if (callback != null) {
      return callback.createDefaultActions();
    }
    return new Action[0];
  }

  @Override
  public Lookup getLookup() {
    return lookup;
  }

  @Override
  public void componentOpened() {
  }

  @Override
  public void componentClosed() {
  }

  @Override
  public void componentShowing() {
  }

  @Override
  public void componentHidden() {
  }

  @Override
  public void componentActivated() {
  }

  @Override
  public void componentDeactivated() {
  }

  @Override
  public UndoRedo getUndoRedo() {
    return UndoRedo.NONE;
  }

  @Override
  public void setMultiViewCallback(MultiViewElementCallback callback) {
    this.callback = callback;
  }

  @Override
  public CloseOperationState canCloseElement() {
    return CloseOperationState.STATE_OK;
  }
  
  public static final class Description implements MultiViewDescription, java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private final Image icon;
    private final YearMonth month;
    private final DbInfo dbInfo;

    public Description(Image icon, YearMonth month, DbInfo dbInfo) {
      this.icon = icon;
      this.month = month;
      this.dbInfo = dbInfo;
    }

    @Override
    public int getPersistenceType() {
      return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public String getDisplayName() {
      return "Items";
    }

    @Override
    public Image getIcon() {
      return icon;
    }

    @Override
    public HelpCtx getHelpCtx() {
      return null;
    }

    @Override
    public String preferredID() {
      return "MonthItemsEditor";
    }

    @Override
    public MultiViewElement createElement() {
      return new MonthEditorPanel(month, dbInfo);
    }
  }
}
