/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mox.nbevid.explorer.editors;


import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mox.nbevid.model.ItemType;
import org.openide.util.ChangeSupport;


/**
 *
 * @author martin
 */
public class NewItemPanel extends javax.swing.JPanel {
  private static final long serialVersionUID = 1L;
  
  private final ChangeSupport changeSupport = new ChangeSupport(this);

  /**
   * Creates new form NewItemPanel
   */
  public NewItemPanel() {
    initComponents();
    
    DocumentListener docListener = new DocumentListener() {
      @Override
      public void insertUpdate(DocumentEvent e) {
        changeSupport.fireChange();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        changeSupport.fireChange();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        changeSupport.fireChange();
      }
    };
    
    itemNameTextField.getDocument().addDocumentListener(docListener);
  }
  
  public void addChangeListener(ChangeListener l) {
    changeSupport.addChangeListener(l);
  }
  
  public void removeChangeListener(ChangeListener l) {
    changeSupport.removeChangeListener(l);
  }
  
  public boolean validateValues() {
    if (itemNameTextField.getText().isEmpty()) {
      return false;
    }
    
    return itemTypeIncomeRadioButton.isSelected() ^ itemTypeSpendingRadioButton.isSelected();
  }
  
  public String getItemName() {
    return itemNameTextField.getText();
  }
  
  public ItemType getItemType() {
    return itemTypeIncomeRadioButton.isSelected() ? ItemType.INCOME : ItemType.SPENDING;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    itemTypeButtonGroup = new javax.swing.ButtonGroup();
    itemNameLabel = new javax.swing.JLabel();
    itemNameTextField = new javax.swing.JTextField();
    itemTypeLabel = new javax.swing.JLabel();
    itemTypeSpendingRadioButton = new javax.swing.JRadioButton();
    itemTypeIncomeRadioButton = new javax.swing.JRadioButton();

    itemNameLabel.setLabelFor(itemNameTextField);
    org.openide.awt.Mnemonics.setLocalizedText(itemNameLabel, org.openide.util.NbBundle.getMessage(NewItemPanel.class, "NewItemPanel.itemNameLabel.text", new Object[] {})); // NOI18N

    itemNameTextField.setText(org.openide.util.NbBundle.getMessage(NewItemPanel.class, "NewItemPanel.itemNameTextField.text", new Object[] {})); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(itemTypeLabel, org.openide.util.NbBundle.getMessage(NewItemPanel.class, "NewItemPanel.itemTypeLabel.text", new Object[] {})); // NOI18N

    itemTypeButtonGroup.add(itemTypeSpendingRadioButton);
    itemTypeSpendingRadioButton.setSelected(true);
    org.openide.awt.Mnemonics.setLocalizedText(itemTypeSpendingRadioButton, org.openide.util.NbBundle.getMessage(NewItemPanel.class, "NewItemPanel.itemTypeSpendingRadioButton.text", new Object[] {})); // NOI18N
    itemTypeSpendingRadioButton.setToolTipText(org.openide.util.NbBundle.getMessage(NewItemPanel.class, "NewItemPanel.itemTypeSpendingRadioButton.toolTipText", new Object[] {})); // NOI18N

    itemTypeButtonGroup.add(itemTypeIncomeRadioButton);
    org.openide.awt.Mnemonics.setLocalizedText(itemTypeIncomeRadioButton, org.openide.util.NbBundle.getMessage(NewItemPanel.class, "NewItemPanel.itemTypeIncomeRadioButton.text", new Object[] {})); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(itemNameLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(itemNameTextField))
          .addGroup(layout.createSequentialGroup()
            .addComponent(itemTypeLabel)
            .addGap(18, 18, 18)
            .addComponent(itemTypeSpendingRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(itemTypeIncomeRadioButton)
            .addGap(0, 157, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(itemNameLabel)
          .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(itemTypeLabel)
          .addComponent(itemTypeSpendingRadioButton)
          .addComponent(itemTypeIncomeRadioButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel itemNameLabel;
  private javax.swing.JTextField itemNameTextField;
  private javax.swing.ButtonGroup itemTypeButtonGroup;
  private javax.swing.JRadioButton itemTypeIncomeRadioButton;
  private javax.swing.JLabel itemTypeLabel;
  private javax.swing.JRadioButton itemTypeSpendingRadioButton;
  // End of variables declaration//GEN-END:variables
}
