/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mox.nbevid.explorer.nodes;


import java.text.ParseException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;
import mox.nbevid.model.Item;
import mox.nbevid.model.SpendingsDatabase;
import org.openide.util.ChangeSupport;


/**
 *
 * @author martin
 */
public class NewYearPanel extends javax.swing.JPanel {
  private static final long serialVersionUID = 1L;
  
  private final SpinnerNumberModel yearModel;
  private final SpendingsDatabase dbModel;
  
  private final ChangeSupport changeSupport = new ChangeSupport(this);

  /**
   * Creates new form NewYearPanel
   */
  public NewYearPanel(int proposedYear, SpendingsDatabase dbModel) {
    this.yearModel = new SpinnerNumberModel(proposedYear, proposedYear - 100, proposedYear + 100, 1);
    this.dbModel = dbModel;
    
    initComponents();
  }
  
  public void addChangeListener(ChangeListener l) {
    changeSupport.addChangeListener(l);
  }
  
  public void removeChangeListener(ChangeListener l) {
    changeSupport.removeChangeListener(l);
  }
  
  public boolean validateValues() {
    int selectedYear = getSelectedYear();
    if (selectedYear <= 0) {
      return false;
    }
    for (int yi : dbModel.getYearKeys()) {
      if (yi == selectedYear) {
        return false;
      }
    }
    
    return true;
  }
  
  public int getSelectedYear() {
    try {
      yearSpinner.commitEdit();
    } catch (ParseException ex) {
      return -1;
    }
    return yearModel.getNumber().intValue();
  }
  
  public List<Item> getSelectedItems() {
    // TODO: zatial fake - vraciam vsetky itemy zotriedene podla id
    ArrayList<Item> items = new ArrayList<>(dbModel.getAllItems().values());
    items.sort(Comparator.comparingInt(item -> item.getItemId()));
    return items;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    yearLabel = new javax.swing.JLabel();
    yearSpinner = new javax.swing.JSpinner();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    org.openide.awt.Mnemonics.setLocalizedText(yearLabel, org.openide.util.NbBundle.getMessage(NewYearPanel.class, "NewYearPanel.yearLabel.text", new Object[] {})); // NOI18N

    yearSpinner.setModel(this.yearModel);
    yearSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(yearSpinner, "#"));

    jLabel1.setForeground(new java.awt.Color(255, 0, 51));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NewYearPanel.class, "NewYearPanel.jLabel1.text", new Object[] {})); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(yearLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(yearLabel)
          .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel yearLabel;
  private javax.swing.JSpinner yearSpinner;
  // End of variables declaration//GEN-END:variables
}
